## 1)

1-1

In [1]:
import random as rd

number = [rd.random() for i in range(100)]
sort_num = sorted(number)
for i in sort_num:
    print(i)

0.011371489482366437
0.03107022951428451
0.036578995527092206
0.04746081903586419
0.04853693031426132
0.0706809841039503
0.08018926209477495
0.08559055040399055
0.09038831213660392
0.10179213440398827
0.11092483211716109
0.11797729804196933
0.12080054172791044
0.15992000028000686
0.172430589834485
0.17262885438935782
0.17527365776298043
0.17560985122415818
0.17834739067195582
0.21114321086352006
0.22254292073191484
0.23618672021994036
0.25206078003627275
0.25850811028416754
0.2695585356482427
0.275522046747244
0.2814619059976433
0.2838830481858887
0.29278739832882184
0.29384042825200574
0.30046604210461636
0.30192178786703217
0.3235609333069187
0.33039661731510195
0.33057004763152964
0.33917429072088257
0.3465734954580115
0.35144336214761274
0.42214831837575606
0.43488436227051974
0.4420945575726807
0.44992672916657883
0.45887799347978075
0.46744438659744125
0.4704558542713255
0.48226738854628637
0.48239898895897537
0.498206250482652
0.5097581382419566
0.5184703464361728
0.526870747004

1-2

In [46]:
import numpy as np

A = np.random.rand(4,4)*10
B = np.random.rand(4,4)*10
C = np.zeros((4, 4))

for i in range(4):
    for j in range(4):
        for k in range(4):
            C[i,j] += A[i,k] * B[k,j]

inv_C = np.zeros((4, 4))
adj_C = np.zeros((4, 4))
det_C = np.linalg.det(C)

if det_C != 0:
    for i in range(4):
        for j in range(4):
            adj_C[i,j] = (-1)**(i+j)\
            *np.linalg.det(np.delete(np.delete(C, i, axis=1), j, axis=0))

    inv_C = adj_C / det_C

ide_Mat = np.zeros((4, 4))

for i in range(4):
    for j in range(4):
        for k in range(4):
            ide_Mat[i,j] += C[i,k] * inv_C[k,j]

np.set_printoptions(precision=3, suppress=True)
print(A)
print("===========================")
print(B)
print("===========================")
print(C)
print("===========================")
print(inv_C)
print("===== Identity Matrix =====")
print(ide_Mat)

[[4.522 5.426 7.209 3.141]
 [8.965 8.514 4.211 3.915]
 [0.087 1.156 6.991 7.144]
 [0.405 4.292 0.704 1.155]]
[[7.694 2.542 4.356 2.161]
 [7.074 2.751 2.777 8.717]
 [5.961 8.213 6.418 4.097]
 [5.876 6.078 4.308 3.094]]
[[134.617 104.724  94.57   96.324]
 [177.314 104.587 106.585 122.952]
 [ 92.514 104.243  79.239  61.013]
 [ 44.466  25.642  23.18   44.747]]
[[-0.183  0.1    0.082  0.008]
 [-0.172  0.058  0.108  0.061]
 [ 0.372 -0.152 -0.191 -0.123]
 [ 0.088 -0.054 -0.044  0.043]]
===== Identity Matrix =====
[[ 1. -0.  0.  0.]
 [ 0.  1.  0.  0.]
 [-0. -0.  1.  0.]
 [ 0. -0.  0.  1.]]


## 2)

### 1. Bisection Method

In [48]:
def f(x):
    return x**5 - 9*x**4 - x**3 + 17*x**2 - 8*x - 8

def bisection_method(f, a, b, tol=5e-12, max_iter=50):
    if f(a) * f(b) > 0:
        print("근이 존재하지 않는 구간입니다.")
        return None

    iter_count = 0
    while abs(b - a) > tol and iter_count < max_iter:
        c = (a + b) / 2

        if f(c) == 0:
            return c
        
        if f(a) * f(c) < 0:
            b = c
        else:
            a = c
        iter_count += 1

    return (a + b) / 2, iter_count

root1, count1 = bisection_method(f, -10, -1)
root2, count2 = bisection_method(f, -1, 0)
root3, count3 = bisection_method(f, 0, 10)

print("첫 번째 근:", format(root1, ".8f"))
print("두 번째 근:", format(root2, ".8f"))
print("세 번째 근:", format(root3, ".8f"))

print(count1, count2, count3)

첫 번째 근: -1.38750711
두 번째 근: -0.51042934
세 번째 근: 8.91069640
41 38 41


### 2. Newton's Method

In [43]:
def f(x):
    return x**5 - 9*x**4 - x**3 + 17*x**2 - 8*x - 8

def dfdx(x):
    return 5*x**4 - 36*x**3 - 3*x**2 + 34*x - 8

def newton_method(f, p, tol=5e-12, max_iter=50):
    
    iter_count = 0
    while abs(f(p)) > tol and iter_count < max_iter:
        if dfdx(p) == 0:
            break
        
        p_new = p - f(p)/dfdx(p)
        p = p_new
        iter_count += 1

    return p, iter_count

root1, count1 = newton_method(f, -10)
root2, count2 = newton_method(f, -0.1)
root3, count3 = newton_method(f, 10)

print("첫 번째 근:", format(root1, ".8f"))
print("두 번째 근:", format(root2, ".8f"))
print("세 번째 근:", format(root3, ".8f"))

print(count1, count2, count3)

첫 번째 근: -1.38750711
두 번째 근: -0.51042934
세 번째 근: 8.91069640
13 5 6


### 3. Newton's Method (x=0)

In [32]:
def f(x):
    return x**5 - 9*x**4 - x**3 + 17*x**2 - 8*x - 8

def dfdx(x):
    return 5*x**4 - 36*x**3 - 3*x**2 + 34*x - 8

def newton_method(f, p, tol=1e-12, max_iter=50):

    iter_count = 0
    while abs(f(p)) > tol and iter_count < max_iter:
        p_new = p - f(p)/dfdx(p)
        p = p_new
        
        iter_count += 1
        
    return p

root = newton_method(f, 0)

print("초기조건을 0으로 하였을 때의 근:", format(root, ".8f"))

초기조건을 0으로 하였을 때의 근: 1.00000000


### 4. Secant Method

In [45]:
def f(x):
    return x**5 - 9*x**4 - x**3 + 17*x**2 - 8*x - 8

def secant_method(f, p_old, p, tol=5e-12, max_iter=50):
    
    iter_count = 0
    while abs(f(p)) > tol and iter_count < max_iter:
        denominator = f(p) - f(p_old)
        if denominator == 0:
            break

        p_new = p - f(p)*((p-p_old)/denominator)
        p_old = p
        p = p_new
        iter_count += 1
        
    return p, iter_count

root1, count1 = secant_method(f, -10, -9.9)
root2, count2 = secant_method(f, -0.1, -0.2)
root3, count3 = secant_method(f, 10, 9.9)

print("첫 번째 근:", format(root1, ".8f"))
print("두 번째 근:", format(root2, ".8f"))
print("세 번째 근:", format(root3, ".8f"))

print(count1, count2, count3)

첫 번째 근: -1.38750711
두 번째 근: -0.51042934
세 번째 근: 8.91069640
18 6 8
